development:
  contact_receiver: <%= ENV["CONTACT_RECEIVER"] || "steve@grouch.dev" %>
  mailer_sender: <%= ENV["MAILER_SENDER"] || "robut@grouch.dev" %>

production:
  contact_receiver: <%= ENV["CONTACT_RECEIVER"] || "steve@grouch.dev" %>
  mailer_sender: <%= ENV["MAILER_SENDER"] || "robut@grouch.dev" %>
  secret_key_base: e2e8ce86b0a97ce32c722c796011e54c6342dbf4c0b72b2074b224c41917a2cba287f8f3db5fcdf5b0fc12b593c352ad41a01cda74315ada6fb1b9f7db0a56b5
